import Head from "next/head";
import { Container, Main, Title, Description, CodeTag } from "components/sharedstyles";
import Cards from "components/cards";
import { useEffect, useState } from "react";
import ReceiptItemLiest from "@/components/organisms/ReceiptItemList/ReceiptItemLiest";
import useHandlers from "@/hooks/useHandlers";
import { createId } from "@paralleldrive/cuid2";
import { ReceiptFetched } from "@/models/ReceiptsFetched";

const initialFormState = {
   // id: "",
   // vehicle: { id: "", name: "", licensePlate: "" },
   // name: "",
   // licensePlate: "",
   date: "",
   odometer: "",
   liters: "",
   pricePerLiter: "",
   currency: "EUR",
   valueAddedTax: 19,
   vehicleId: "",
};

const Home = () => {
   const [receipts, setReceipts] = useState<ReceiptFetched[] | null>(null);
   const [formValues, setFormValues] = useState(initialFormState);
   const [isLoading, setIsLoading] = useState(false);
   const [error, setError] = useState("");
   // console.log(formValues);

   useEffect(() => {
      const getData = async () => {
         try {
            setError("");
            setIsLoading(true);
            const resolve = await fetch("/api/receipts");

            const data: ReceiptFetched[] = await resolve.json();
            console.log(data);
            setReceipts(data);
         } catch (err) {
            setError(err.message);
            console.error(err);
         } finally {
            setIsLoading(false);
         }
      };
      getData();
   }, []);
   console.log(receipts);

   const handleInputChange = (e) => {
      // console.log(e.target.name);
      setFormValues({
         ...formValues,
         [e.target.name]: e.target.value,
      });
      // console.log(e.target.name);
   };
   const handleDelete = (e) => {
      // console.log(e);
   };
   const handleAddReceipt = async (e) => {
      e.preventDefault();

      //new object creating-neueBelege:
      const newReceiptObj: ReceiptFetched = {
         // id: createId(),
         // vehicle: { id: createId(), name: formValues.name, licensePlate: formValues.licensePlate },
         date: "2023-02-10T00:00:00.000Z",
         // date: Date.now().toString(),
         odometer: Number.parseInt(formValues.odometer),
         liters: Number.parseFloat(formValues.liters),
         pricePerLiter: Number.parseFloat(formValues.pricePerLiter),
         currency: "EUR",
         valueAddedTax: 19,
         vehicleId: formValues.vehicleId,
      };

      // console.log(receipts);
      setFormValues(initialFormState); //clearing the Form
      // post request sending:
      setReceipts([...receipts, newReceiptObj]); // state updating-Belegeliste
      const res = await fetch("/api/receipts", {
         method: "POST",
         headers: {
            "Content-Type": "application/json",
         },
         body: JSON.stringify(newReceiptObj),
      });
      const newReceipt = await res.json();

      // checking res if is false:
      if (!res.ok) {
         console.log("Failed to send data.");
      }

      // checking res if is true
      if (res.ok) {
         console.log("Success", newReceipt);
      }
   };
   // console.log(handleAddReceipt());
   if (isLoading) {
      return (
         <div>
            <p>Loading...</p>
         </div>
      );
   }

   if (error) {
      return (
         <div>
            <p>{error}</p>
         </div>
      );
   }

   return (
      <Container>
         <Head>
            <title>Eine Liste der Tankbelege</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Main>
            <Title>Eine Liste der Tankbelege:</Title>
            <form onSubmit={handleAddReceipt}>
               <select name="vehicleId" onChange={handleInputChange} value={formValues.vehicleId}>
                  <option value="">Choose the Car</option>
                  <option value="clhvmqzdk0006mj08ftyjig9s">Cupra Formentor HD-TA-X44</option>
                  <option value="clhvmqzcj0002mj081no5h0m0">VW Passat HD-TA-X12</option>
                  <option value="clhvmqzd20004mj08fqaccv59">Seat Leon HD-TA-X20</option>
               </select>
               <input type="text" placeholder="...vehicleId" name="vehicleId" value={formValues.vehicleId} onChange={handleInputChange} />
               {/* <input
                  type="text"
                  placeholder="...vehicle.licensePlate"
                  name="licensePlate"
                  value={formValues.licensePlate}
                  onChange={handleInputChange}
               /> */}
               {/* <input placeholder="...date" name="date" value={formValues.date} onChange={handleInputChange} /> */}
               <input type="text" placeholder="...odometer" onChange={handleInputChange} name="odometer" value={formValues.odometer} />
               <input type="number" placeholder="...liters" onChange={handleInputChange} name="liters" value={formValues.liters} />
               <input
                  type="number"
                  placeholder="...pricePerLiter"
                  onChange={handleInputChange}
                  name="pricePerLiter"
                  value={formValues.pricePerLiter}
               />
               {/* <input type="text" placeholder="...currency" onChange={handleInputChange} name="currency" value={formValues.currency} /> */}
               {/* <input type="text" placeholder="...valueAddedTax" onChange={handleInputChange} name="valueAddedTax" value={formValues.valueAddedTax} /> */}

               <button type="submit">Add</button>
            </form>
            <ReceiptItemLiest receipeets={receipts} handleDelete2={handleDelete} />
            <Description>
               <CodeTag>pages/index.tsx</CodeTag>
            </Description>

            <Cards />
         </Main>
      </Container>
   );
};

export default Home;
